version: '3'

services:
  home-dashboard:
    #restart: unless-stopped
    image: node:lts-alpine
    command: >
      sh -c "cd /app &&
             npm install &&
             npm run dev"
    volumes:
      - .:/app
    ports:
      - 3000:3000
