version: '3'

services:
  home-dashboard:
    #restart: unless-stopped
    image: node:lts
    command: >
      bash -c "cd /app &&
               npm install -f &&
               npm run start"
    volumes:
      - .:/app
    ports:
      - 3001:3000
