version: '3'

services:
  web:
    image: node:lts-alpine
    command: >
      sh -c "cd /app &&
             npm install &&
             npm run dev"
    volumes:
      - ./web/:/app
    ports:
      - 3000:3000
  api:
    image: python:3-slim
    command: >
      sh -c "cd /app && 
            pip install -r /app/requirements.txt && 
            uvicorn main:app --host 0.0.0.0 --port 80 --reload"
    volumes:
      - ./api/:/app
    ports:
      - 5000:80
    environment:
      - TWITTER_CONSUMER_KEY=${TWITTER_CONSUMER_KEY}
      - TWITTER_CONSUMER_SECRET=${TWITTER_CONSUMER_SECRET}
      - TWITTER_ACCESS_TOKEN=${TWITTER_ACCESS_TOKEN}
      - TWITTER_ACCESS_TOKEN_SECRET=${TWITTER_ACCESS_TOKEN_SECRET}
      - API_KEY=${API_KEY}
      - ALLOW_ORIGINS=${ALLOW_ORIGINS}
      - ENABLE_DOCS=${ENABLE_DOCS}
