name: API deploy to Dokku

on:
  push:
    branches:
      - master
    paths:
      - 'api/**'
      - '.github/workflows/api-dokku.yml'

env:
  REMOTE_URL: ${{ secrets.REMOTE_URL }}
  REMOTE_PRIVATE_KEY: ${{ secrets.REMOTE_PRIVATE_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: ${{ env.REMOTE_URL }}
          ssh_private_key: ${{ env.REMOTE_PRIVATE_KEY }}
