name: Web Deploy on Github Pages

on:
  push:
    branches:
      - master
    paths:
      - 'web/**'
      - '.github/workflows/web-github-pages.yml'

env:
  REPOSITORY: ${{ secrets.REPOSITORY }}
  USER_NAME: ${{ secrets.USER_NAME }}
  USER_EMAIL: ${{ secrets.USER_EMAIL }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: NPM Instal and Build
        run: |
          cd web
          npm install
          npm run build
      - name: Deploy 
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: master 
          folder: web/dist 
          repository-name: ${{ env.REPOSITORY }}
          git-config-name: ${{ env.USER_NAME }}
          git-config-email: ${{ env.USER_EMAIL }}
          ssh-key: ${{ secrets.GP_KEY }}
